= AdminFaces
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:docinfo:
:includedir: _includes
:experimental:

:projectRoot: ../../..

:link-adminfaces: http://github.com/adminfaces
:link-admin-site: http://adminfaces.github.io/site
:link-admin-showcase: {link-adminfaces}/admin-showcase
:link-admin-showcase-openshift: https://adminfaces.github.io/admin-showcase/
:link-admin-starter-openshift: https://adminfaces.github.io/admin-starter/
:link-admin-starter: {link-adminfaces}/admin-starter
:link-admin-template: {link-adminfaces}/admin-template
:link-docs-github: http://adminfaces.github.io/docs
:link-admin-theme: {link-adminfaces}/admin-theme
:link-admin-designer: {link-adminfaces}/admin-designer
:link-admin-addon: {link-adminfaces}/admin-addon
:link-admin-persistence: {link-adminfaces}/admin-persistence
:link-admin-starter-tomcat: {link-adminfaces}/admin-starter-tomcat
:link-admin-starter-persistence: {link-adminfaces}/admin-starter-persistence
:link-admin-starter-springboot: {link-adminfaces}/admin-starter-springboot
:link-admin-starter-springsecurity:  {link-adminfaces}/admin-starter-springboot-security
:link-admin-starter-shiro: {link-adminfaces}/admin-starter-shiro
:link-admin-starter-security: {link-adminfaces}/admin-starter-security
:link-admin-mobile: {link-adminfaces}/admin-mobile
:link-jboss-forge: https://forge.jboss.org/

:link-jsf: https://javaserverfaces.java.net/
:link-primefaces: http://primefaces.org
:link-bootstrap: http://getbootstrap.com/
:link-adminlte: https://adminlte.io/themes/AdminLTE/
:link-less: http://lesscss.org/


ifeval::["{backend}" == "html5"]
icon:file-pdf-o[] Read this documentation {link-admin-docs}/index.pdf[in PDF here, role="external", window="_blank"].
endif::[]

ifeval::["{backend}" == "pdf"]
icon:html5[] Read this documentation {link-admin-docs}/[in HTML5 here, role="external", window="_blank"].
endif::[]

== Introduction

{link-admin-site}[AdminFaces] is an open source project which brings {link-bootstrap}[Bootstrap^] and {link-adminlte}[AdminLTE^] to your application via a {link-primefaces}[PrimeFaces^] theme and a {link-jsf}[JSF^] `responsive` template.

AdminFaces ecosystem is composed by the following projects:

* {link-admin-theme}[Admin Theme^]: A Primefaces theme based on {link-bootstrap}[Bootstrap^] and {link-adminlte}[Admin LTE^] where {link-primefaces}[Primefaces^] components are customized to look like mentioned frameworks.
* {link-admin-template}[Admin Template^]: A *fully responsive* {link-jsf}[Java Server Faces^] `admin` template which is also based on *Bootstrap* and *Admin LTE*.
* {link-admin-showcase}[Admin Showcase^]: A showcase web application, {link-admin-showcase-openshift}[deployed on openshift^], which demonstrates AdminFaces main features and components.
* {link-admin-designer}[Admin Designer^]: The same showcase application with Admin Theme and Admin Template bundled (instead of being library dependencies) in order to make it easier to customize the theme and the template.
* A variety of `<<Admin Starters,starters projects>>` to help you get started with AdminFaces and your favorite stack.  
* {link-admin-persistence}[Admin Persistence^]: CRUD operations like a breeze for AdminFaces applications based on https://deltaspike.apache.org/documentation/data.html[Apache DeltaSpike Data^] module.
* {link-admin-addon}[Admin Addon^]: Enables `scaffold from entities` (and much more) for AdminFaces applicatons.
* {link-admin-mobile}[Admin Mobile^]: A simple https://developer.android.com/studio/index.html[Android Studio^] project which uses https://developer.android.com/reference/android/webkit/WebView.html[Webview^] to create an https://www.mobiloud.com/blog/native-web-or-hybrid-apps/[hybrid web app^] based on Admin Showcase.

In subsequent chapters we will drive through each project in detail.

TIP: Watch the version 1.0 announcement video to get a better idea: https://www.youtube.com/watch?v=kg_L8WjOGP8

include::{includedir}/01-theme.adoc[leveloffset=+1]

include::{includedir}/02-template.adoc[leveloffset=+1]

include::{includedir}/03-showcase.adoc[leveloffset=+1]

include::{includedir}/03-starters.adoc[leveloffset=+1]

include::{includedir}/04-designer.adoc[leveloffset=+1]

include::{includedir}/05-persistence.adoc[leveloffset=+1]

include::{includedir}/06-scaffold.adoc[leveloffset=+1]

include::{includedir}/07-mobile.adoc[leveloffset=+1]
